[package]
name = "mexl"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde_json = ["dep:serde_json"]

[dependencies]
serde_json = { version = "1.0", optional = true }
thiserror = "2.0.18"
